# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simplenote}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simon Jefford"]
  s.date = %q{2009-09-03}
  s.description = %q{Uses HTTParty to present a nice Ruby wrapper for SimpleNote}
  s.email = %q{simon.jefford@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/simplenote.rb",
     "test/simplenote_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/simonjefford/simplenote}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple wrapper for the SimpleNote HTTP API}
  s.test_files = [
    "test/simplenote_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<crack>, [">= 0"])
      s.add_development_dependency(%q<jnunemaker-matchy>, [">= 0"])
      s.add_development_dependency(%q<jferris-mocha>, ["= 0.9.5.0.1241126838"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<crack>, [">= 0"])
      s.add_dependency(%q<jnunemaker-matchy>, [">= 0"])
      s.add_dependency(%q<jferris-mocha>, ["= 0.9.5.0.1241126838"])
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<crack>, [">= 0"])
    s.add_dependency(%q<jnunemaker-matchy>, [">= 0"])
    s.add_dependency(%q<jferris-mocha>, ["= 0.9.5.0.1241126838"])
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end
